# Generated by Django 4.1.7 on 2023-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("news_details", models.TextField()),
                ("cover_image", models.ImageField(upload_to="profile_pics/")),
            ],
        ),
    ]
