# Generated by Django 4.1.7 on 2023-02-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewsInfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsinformation",
            name="cover_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
